;;;; cairo-utils.import.scm - GENERATED BY CHICKEN 4.10.0 -*- Scheme -*-

(eval '(import scheme chicken sdl2 cairo clojurian-syntax srfi-1 srfi-4))
(##sys#register-compiled-module
  'cairo-utils
  (list)
  '((*cairo-context* . cairo-utils#*cairo-context*)
    (frequency . cairo-utils#frequency)
    (solid-white . cairo-utils#solid-white)
    (solid-black . cairo-utils#solid-black)
    (font-color . cairo-utils#font-color)
    (font-size . cairo-utils#font-size)
    (current-background . cairo-utils#current-background)
    (init-utils! . cairo-utils#init-utils!)
    (text-width . cairo-utils#text-width)
    (text . cairo-utils#text)
    (clear-screen . cairo-utils#clear-screen)
    (filled-rectangle . cairo-utils#filled-rectangle)
    (draw-line . cairo-utils#draw-line)
    (show! . cairo-utils#show!)
    (for-events . cairo-utils#for-events)
    (map-events . cairo-utils#map-events))
  (list)
  (list))

;; END OF FILE
